server:
  port: 9090

spring:
  application:
    name: auth-server
  security:
    user:
      name: myuser
      password: mypassword
    oauth2:
      authorizationserver:
        issuer: http://authorization-server.local.com:9090
        client:
          game-server-client:
            registration:
              client-id: game-server-client
              client-secret: "{noop}game-server-secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://game-server:7070/login/oauth2/code/game-server-client"
                - "http://game-server:7070/games"
              post-logout-redirect-uris:
                - "http://authorization-server.local.com:9090/after-logout"
              scopes:
                - "openid"
                - "profile"
            token:
              access-token-time-to-live: 3600s
      client:
        registration:
          google-client:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/auth"
            token-uri: "https://oauth2.googleapis.com/token"

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: TRACE